language: python
python:
  - '3.7'
sudo: false
cache:
  directories:
    - "~/.platformio"
env:
  - NODE_VERSION="10"
before_install:
  - nvm install $NODE_VERSION
install:
  - pip3 install -U platformio
  - platformio lib install
script:
  - platformio run
before_deploy:
  - ./.prepare_release
deploy:
  provider: releases
  prerelease: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  skip_cleanup: true
  file: dist/*.bin
  on:
    repo: sidoh/epaper_templates
    tags: true
